services:
  - type: web
    name: clashroyale-analytics-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: ClashRoyaleApi__BaseUrl
        value: https://api.clashroyale.com/v1/
      - key: ClashRoyaleApi__ApiToken
        sync: false
      - key: Security__AllowedOrigins__0
        value: https://clashroyaleanalyticswebapp.vercel.app
      - key: Security__AllowedOrigins__1
        value: https://clashroyaleanalyticswebapp-7fe2w3fow.vercel.app
      - key: Security__AllowedOrigins__2
        value: http://127.0.0.1:5500
      - key: Security__AllowedOrigins__3
        value: http://localhost:5500
